### ISSUE TITLE
'TopicTabooPlugin' object has no attribute 'topic_config'

### ISSUE THREAD

**Issue by wangnuannuan** [beerfactory/hbmqtt#137]
when I install the hbmqtt by "pip install hbmqtt", there was an error  in the file name "clinet.py", line 21;
Then i install it by using "setup.py", and the error is "AttributeError: 'TopicTabooPlugin' object has no attribute 'topic_config'" in the file named "plugins/topic_checking.py",line 13.

**Comment by Kriechi** [comment]
How did you fix this? I am getting the same error.

**Comment by fg607** [comment]
@wangnuannuan @Kriechi u can add it to default_broker.yaml manually like this

```
listeners:
  default:
    type: tcp
    bind: 0.0.0.0:1883
sys_interval: 20
auth:
  allow-anonymous: true
plugins:
  - auth_file
  - auth_anonymous
topic-check:
  enabled': True
  plugins': 
    - topic_taboo
```
